//Given an array of integers, every element appears twice except for one. Find that single one.


int singleNumber(vector<int>& a) {
     int n = a.size();
     int num = 0;
     for (int i = 0; i < n; ++i) {
         num ^= a[i];
     }
     return num;
}

//  Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
// Example:
// Input:
// s = "abcd"
// t = "abcde"
// Output:
// e
// Explanation:
// 'e' is the letter that was added.


 char findTheDifference(string s, string t) {
      char r=0;
        for(char c:s) r ^=c;
        for(char c:t) r ^=c;
        return r;
  }